# Generated by Django 5.2.17 on 2026-09-13 17:03

import django.contrib.postgres.indexes
import django.contrib.postgres.search
import django.db.models.deletion
import pgvector.django.indexes
import pgvector.django.vector
from pgvector.django import VectorExtension
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        # dev/postgres/initdb/ also creates this, but a migration that
        # depends on an init script only runs in the one environment
        # that has the script. ops/ and CI create databases their own way.
        VectorExtension(),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=128, unique=True)),
                ('title', models.TextField()),
                ('filename', models.TextField(help_text='Name of the file as ingested.')),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('byte_size', models.BigIntegerField()),
                ('media_type', models.CharField(default='application/pdf', max_length=128)),
                ('page_count', models.IntegerField(blank=True, null=True)),
                ('canonical_text', models.TextField()),
                ('language', models.CharField(default='english', max_length=32)),
                ('extractor', models.CharField(help_text="Library and version that produced canonical_text, e.g. 'pdfplumber/0.11.10'.", max_length=128)),
                ('pipeline_version', models.CharField(max_length=32)),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('heading', 'Heading'), ('paragraph', 'Paragraph'), ('list_item', 'List Item'), ('table', 'Table'), ('front_matter', 'Front Matter')], max_length=16)),
                ('path', models.CharField(blank=True, db_index=True, max_length=128)),
                ('heading', models.TextField(blank=True, help_text="The unit's own title, if it has one.")),
                ('ordinal', models.IntegerField()),
                ('depth', models.IntegerField(default=0)),
                ('start_offset', models.IntegerField()),
                ('end_offset', models.IntegerField()),
                ('page_start', models.IntegerField(blank=True, null=True)),
                ('page_end', models.IntegerField(blank=True, null=True)),
                ('text', models.TextField()),
                ('search_vector', django.contrib.postgres.search.SearchVectorField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='grounding.unit')),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='grounding.source')),
            ],
            options={
                'ordering': ['source', 'ordinal'],
            },
        ),
        migrations.CreateModel(
            name='Embedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vector', pgvector.django.vector.VectorField(dimensions=1536)),
                ('model', models.CharField(max_length=128)),
                ('pipeline_version', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='embeddings', to='grounding.unit')),
            ],
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('start_offset', models.IntegerField()),
                ('end_offset', models.IntegerField()),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='grounding.source')),
            ],
            options={
                'ordering': ['source', 'number'],
                'constraints': [models.UniqueConstraint(fields=('source', 'number'), name='unique_page_per_source')],
            },
        ),
        migrations.AddIndex(
            model_name='unit',
            index=models.Index(fields=['source', 'path'], name='grounding_u_source__5a945d_idx'),
        ),
        migrations.AddIndex(
            model_name='unit',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='unit_search_vector_gin'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.UniqueConstraint(fields=('source', 'ordinal'), name='unique_ordinal_per_source'),
        ),
        migrations.AddConstraint(
            model_name='unit',
            constraint=models.CheckConstraint(condition=models.Q(('end_offset__gt', models.F('start_offset'))), name='unit_range_is_non_empty'),
        ),
        migrations.AddIndex(
            model_name='embedding',
            index=pgvector.django.indexes.HnswIndex(ef_construction=64, fields=['vector'], m=16, name='embedding_vector_hnsw', opclasses=['vector_cosine_ops']),
        ),
        migrations.AddConstraint(
            model_name='embedding',
            constraint=models.UniqueConstraint(fields=('unit', 'model'), name='one_vector_per_unit_per_model'),
        ),
    ]
