# Generated by Django 5.2.17 on 2026-09-13 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounding', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='edition',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
