# Generated by Django 5.2.17 on 2026-09-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grounding', '0003_source_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUsage',
            fields=[
                ('day', models.DateField(primary_key=True, serialize=False)),
                ('model_calls', models.IntegerField(default=0)),
                ('refused_calls', models.IntegerField(default=0, help_text="Questions answered retrieval-only because the day's cap was reached.")),
                ('input_tokens', models.BigIntegerField(default=0)),
                ('output_tokens', models.BigIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'daily usage',
                'ordering': ['-day'],
            },
        ),
    ]
